set(_CATKIN_CURRENT_PACKAGE "cartographer_ros")
set(cartographer_ros_VERSION "1.0.0")
set(cartographer_ros_MAINTAINER "The Cartographer Authors <cartographer-owners@googlegroups.com>")
set(cartographer_ros_PACKAGE_FORMAT "2")
set(cartographer_ros_BUILD_DEPENDS "google-mock" "g++-static" "protobuf-dev" "python-sphinx" "cartographer" "cartographer_ros_msgs" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "libpcl-all-dev" "message_runtime" "nav_msgs" "pcl_conversions" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(cartographer_ros_BUILD_DEPENDS_cartographer_VERSION_GTE "1.0.0")
set(cartographer_ros_BUILD_DEPENDS_cartographer_ros_msgs_VERSION_GTE "1.0.0")
set(cartographer_ros_BUILD_EXPORT_DEPENDS "cartographer" "cartographer_ros_msgs" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "libpcl-all-dev" "message_runtime" "nav_msgs" "pcl_conversions" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(cartographer_ros_BUILD_EXPORT_DEPENDS_cartographer_VERSION_GTE "1.0.0")
set(cartographer_ros_BUILD_EXPORT_DEPENDS_cartographer_ros_msgs_VERSION_GTE "1.0.0")
set(cartographer_ros_BUILDTOOL_DEPENDS "catkin")
set(cartographer_ros_BUILDTOOL_EXPORT_DEPENDS )
set(cartographer_ros_EXEC_DEPENDS "cartographer" "cartographer_ros_msgs" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "libpcl-all-dev" "message_runtime" "nav_msgs" "pcl_conversions" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(cartographer_ros_EXEC_DEPENDS_cartographer_VERSION_GTE "1.0.0")
set(cartographer_ros_EXEC_DEPENDS_cartographer_ros_msgs_VERSION_GTE "1.0.0")
set(cartographer_ros_RUN_DEPENDS "cartographer" "cartographer_ros_msgs" "eigen_conversions" "geometry_msgs" "libgflags-dev" "libgoogle-glog-dev" "libpcl-all-dev" "message_runtime" "nav_msgs" "pcl_conversions" "robot_state_publisher" "rosbag" "roscpp" "roslaunch" "roslib" "sensor_msgs" "std_msgs" "tf2" "tf2_eigen" "tf2_ros" "urdf" "visualization_msgs")
set(cartographer_ros_RUN_DEPENDS_cartographer_VERSION_GTE "1.0.0")
set(cartographer_ros_RUN_DEPENDS_cartographer_ros_msgs_VERSION_GTE "1.0.0")
set(cartographer_ros_TEST_DEPENDS "rosunit")
set(cartographer_ros_DOC_DEPENDS )
set(cartographer_ros_URL_WEBSITE "https://github.com/googlecartographer/cartographer_ros")
set(cartographer_ros_URL_BUGTRACKER "")
set(cartographer_ros_URL_REPOSITORY "")
set(cartographer_ros_DEPRECATED "")