// Generated by gencpp from file navfn/MakeNavPlan.msg
// DO NOT EDIT!


#ifndef NAVFN_MESSAGE_MAKENAVPLAN_H
#define NAVFN_MESSAGE_MAKENAVPLAN_H

#include <ros/service_traits.h>


#include <navfn/MakeNavPlanRequest.h>
#include <navfn/MakeNavPlanResponse.h>


namespace navfn
{

struct MakeNavPlan
{

typedef MakeNavPlanRequest Request;
typedef MakeNavPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakeNavPlan
} // namespace navfn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navfn::MakeNavPlan > {
  static const char* value()
  {
    return "8ffef29bc8b086289124c16a8daa989d";
  }

  static const char* value(const ::navfn::MakeNavPlan&) { return value(); }
};

template<>
struct DataType< ::navfn::MakeNavPlan > {
  static const char* value()
  {
    return "navfn/MakeNavPlan";
  }

  static const char* value(const ::navfn::MakeNavPlan&) { return value(); }
};


// service_traits::MD5Sum< ::navfn::MakeNavPlanRequest> should match 
// service_traits::MD5Sum< ::navfn::MakeNavPlan > 
template<>
struct MD5Sum< ::navfn::MakeNavPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::navfn::MakeNavPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navfn::MakeNavPlanRequest> should match 
// service_traits::DataType< ::navfn::MakeNavPlan > 
template<>
struct DataType< ::navfn::MakeNavPlanRequest>
{
  static const char* value()
  {
    return DataType< ::navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::navfn::MakeNavPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navfn::MakeNavPlanResponse> should match 
// service_traits::MD5Sum< ::navfn::MakeNavPlan > 
template<>
struct MD5Sum< ::navfn::MakeNavPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::navfn::MakeNavPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navfn::MakeNavPlanResponse> should match 
// service_traits::DataType< ::navfn::MakeNavPlan > 
template<>
struct DataType< ::navfn::MakeNavPlanResponse>
{
  static const char* value()
  {
    return DataType< ::navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::navfn::MakeNavPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVFN_MESSAGE_MAKENAVPLAN_H
